### ISSUE TITLE
Ошибки конкурентности

### ISSUE THREAD

**Issue by vporoshok** [mr-maksimov/golang-first#1]
В текущей реализации обработка url и соответственно запросы, чтение, парсинг будут производиться в одной горутине, запускаемой в строке 57. При этом будет запущенно столько горутин, сколько передано адресов, в строке 66. Таким образом, при попытке передать в программу значительное количество адресов, например, 10 миллионов, то программа отведёт под стэк больше 20 ГБ памяти, что довольно много для подобной задачи.

**Comment by mr-maksimov** [comment]
Переделал, теперь вызываю функцию вызова Get и подсчет искомой фразы внутри
urls <- getCountFindInURL(url), и передаю структуру url, count

**Comment by vporoshok** [comment]
Отличная работа!
